# Travis CI build file.

# whitelist (branches that should be built)
branches:
  only:
    - master
    - /^issue.*$/

# the matrix of builds should cover each combination of Swift version
# and platform that is supported. The version of Swift used is specified
# by .swift-version, unless SWIFT_SNAPSHOT is specified.
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: linux
      dist: xenial
      sudo: required
      env: SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT
    - os: osx
      osx_image: xcode10.2
      sudo: required
# Pending Travis Xcode 11 image
#    - os: osx
#      osx_image: xcode11
#      sudo: required
#      env: SWIFT_SNAPSHOT=$SWIFT_DEVELOPMENT_SNAPSHOT

before_install:
  - ./setupKafka.sh
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
- ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
